# Generated by Django 4.2 on 2023-04-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0003_photos_remove_choice_question_delete_greeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperclip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField()),
                ('cid', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=16)),
                ('paperclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.paperclip')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('phone', 'paperclip')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('sign', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('paperclip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.paperclip')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('phone', 'paperclip')},
            },
        ),
    ]
